version: '3.8'
services:
  valkey-node-0:
    image: docker.io/bitnami/valkey-cluster:latest
    container_name: valkey-node-0
    ports:
      - "7000:6379"
    volumes:
      - valkey-cluster_data-0:/bitnami/valkey/data
    environment:
      - VALKEY_PASSWORD=your_password_here
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5
    networks:
      - valkey-cluster
  valkey-node-1:
    image: docker.io/bitnami/valkey-cluster:latest
    container_name: valkey-node-1
    ports:
      - "7001:6379"
    volumes:
      - valkey-cluster_data-1:/bitnami/valkey/data
    environment:
      - VALKEY_PASSWORD=your_password_here
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5
    networks:
      - valkey-cluster
  valkey-node-2:
    image: docker.io/bitnami/valkey-cluster:latest
    container_name: valkey-node-2
    ports:
      - "7002:6379"
    volumes:
      - valkey-cluster_data-2:/bitnami/valkey/data
    environment:
      - VALKEY_PASSWORD=your_password_here
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5
    networks:
      - valkey-cluster
  valkey-node-3:
    image: docker.io/bitnami/valkey-cluster:latest
    container_name: valkey-node-3
    ports:
      - "7003:6379"
    volumes:
      - valkey-cluster_data-3:/bitnami/valkey/data
    environment:
      - VALKEY_PASSWORD=your_password_here
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5
    networks:
      - valkey-cluster
  valkey-node-4:
    image: docker.io/bitnami/valkey-cluster:latest
    container_name: valkey-node-4
    ports:
      - "7004:6379"
    volumes:
      - valkey-cluster_data-4:/bitnami/valkey/data
    environment:
      - VALKEY_PASSWORD=your_password_here
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5
    networks:
      - valkey-cluster
  valkey-node-5:
    image: docker.io/bitnami/valkey-cluster:latest
    container_name: valkey-node-5
    ports:
      - "7005:6379"
    volumes:
      - valkey-cluster_data-5:/bitnami/valkey/data
    depends_on:
      - valkey-node-0
      - valkey-node-1
      - valkey-node-2
      - valkey-node-3
      - valkey-node-4
    environment:
      - VALKEY_PASSWORD=your_password_here
      - REDISCLI_AUTH=your_password_here
      - VALKEY_CLUSTER_REPLICAS=1
      - VALKEY_NODES=valkey-node-0 valkey-node-1 valkey-node-2 valkey-node-3 valkey-node-4 valkey-node-5
      - VALKEY_CLUSTER_CREATOR=yes
    networks:
      - valkey-cluster
volumes:
  valkey-cluster_data-0:
    driver: local
  valkey-cluster_data-1:
    driver: local
  valkey-cluster_data-2:
    driver: local
  valkey-cluster_data-3:
    driver: local
  valkey-cluster_data-4:
    driver: local
  valkey-cluster_data-5:
    driver: local
networks:
  valkey-cluster:
    driver: bridge